services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  twig_extension_bundle.native_configurator:
    class: Prokl\TwigExtensionsPackBundle\Services\TwigConfiguratorNative
    arguments:
      - '@parameter_bag'

  twig_extension_bundle.twig_paths:
    class: Prokl\TwigExtensionsPackBundle\Services\TwigConfiguratorNative
    factory: ['@twig_extension_bundle.native_configurator', 'paths']

  twig_extension_bundle.config:
    class: Prokl\TwigExtensionsPackBundle\Services\TwigConfiguratorNative
    factory: ['@twig_extension_bundle.native_configurator', 'config']

  # Мигратор extensions в Твиг от maximaster.twig.tool.
  Prokl\TwigExtensionsPackBundle\Services\TwigExtensionsBag:
    arguments:
      - !tagged_iterator twig.extension
    tags:
      - { name: bitrix.events.init, module: '', event: onAfterTwigTemplateEngineInited, method: handle, sort: 100 }

  # Мигратор runtimes в Твиг от maximaster.twig.tool.
  Prokl\TwigExtensionsPackBundle\Services\TwigRuntimesBag:
    arguments:
      - !tagged_iterator twig.runtime
    tags:
      - { name: bitrix.events.init, module: '', event: onAfterTwigTemplateEngineInited, method: handle, sort: 100 }

  ##################
  # Twig extensions
  ##################

  # Битриксовые штучки-дрючки.
  bitrix.pieces:
    class: Prokl\TwigExtensionsPackBundle\Twig\Extensions\Bitrix\BitrixPiecesExtension
    arguments: ['%kernel.project_dir%']
    tags:
      - { name: twig.extension }

  # Битриксовые функции.
  Prokl\TwigExtensionsPackBundle\Twig\Extensions\Bitrix\BitrixExtension:
    tags:
      - { name: twig.extension }

  # Супер-глобалы.
  Prokl\TwigExtensionsPackBundle\Twig\Extensions\Bitrix\PhpGlobalsExtension:
    tags:
      - { name: twig.extension }

  # render()
  Prokl\TwigExtensionsPackBundle\Twig\Extensions\Bitrix\RenderExtension:
    class: Prokl\TwigExtensionsPackBundle\Twig\Extensions\Bitrix\RenderExtension
    arguments:
      - '@dispatcher.controller'
      - '@routes.collection'
    calls:
      - setContainer: ['@service_container']
    tags:
      - { name: twig.extension }

  Prokl\TwigExtensionsPackBundle\Twig\Functions\Bitrix\SymfonyTwigPath:
    arguments: ['@routing.utils', '@parameter_bag']
    tags:
      - { name: twig.extension }