services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  twig_extension_bundle.wordpress_config:
    class: Prokl\TwigExtensionsPackBundle\Services\GlobalsTwigNative
    arguments: ['@twig.instance', '%twig.globals%']
    calls:
      - setContainer: ['@service_container']

  twig_extension_bundle.config_init:
    class: Prokl\TwigExtensionsPackBundle\Services\GlobalsTwigNative
    factory: ['@twig_extension_bundle.wordpress_config', 'addGlobals']
    tags: ['service.bootstrap']

  ##################
  # Twig extensions
  ##################

  # Битриксовые штучки-дрючки.
  bitrix.pieces:
    class: Prokl\TwigExtensionsPackBundle\Twig\Extensions\Bitrix\BitrixPiecesExtension
    arguments: ['%kernel.project_dir%']
    tags:
      - { name: twig.extension }

  # Битриксовые функции.
  Prokl\TwigExtensionsPackBundle\Twig\Extensions\Bitrix\BitrixExtension:
    tags:
      - { name: twig.extension }

  # Супер-глобалы.
  Prokl\TwigExtensionsPackBundle\Twig\Extensions\Bitrix\PhpGlobalsExtension:
    tags:
      - { name: twig.extension }

  # render()
  Prokl\TwigExtensionsPackBundle\Twig\Extensions\Bitrix\RenderExtension:
    class: Prokl\TwigExtensionsPackBundle\Twig\Extensions\Bitrix\RenderExtension
    arguments:
      - '@dispatcher.controller'
      - '@routes.collection'
    calls:
      - setContainer: ['@service_container']
    tags:
      - { name: twig.extension }