services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  ##################
  # Twig extensions
  ##################

  # Битриксовые штучки-дрючки.
  bitrix.pieces:
    class: Prokl\TwigExtensionsPackBundle\Twig\Extensions\Bitrix\BitrixPiecesExtension
    arguments: ['%kernel.project_dir%']
    tags:
      - { name: twig.extension }

  # Битриксовые функции.
  Prokl\TwigExtensionsPackBundle\Twig\Extensions\Bitrix\BitrixExtension:
    tags:
      - { name: twig.extension }

  # Супер-глобалы.
  Prokl\TwigExtensionsPackBundle\Twig\Extensions\Bitrix\PhpGlobalsExtension:
    tags:
      - { name: twig.extension }

  # render()
  Prokl\TwigExtensionsPackBundle\Twig\Extensions\Bitrix\RenderExtension:
    class: Prokl\TwigExtensionsPackBundle\Twig\Extensions\Bitrix\RenderExtension
    arguments:
      - '@dispatcher.controller'
      - '@routes.collection'
    calls:
      - setContainer: ['@service_container']
    tags:
      - { name: twig.extension }