services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  # Глобальные переменные Twig (не используется - ToDo!).
  twig.variables:
    class: Prokl\TwigExtensionsPackBundle\Services\ConfigureVariables
    arguments: ['@app.twig.variable']

  Prokl\TwigExtensionsPackBundle\Services\ConfigureVariables: '@twig.variables'

  ##################
  # Twig extensions
  ##################

  Prokl\TwigExtensionsPackBundle\Twig\Functions\SymfonyTwigPath:
    arguments: ['@routing.utils', '@parameter_bag']
    tags:
      - { name: twig.extension }

  # Функции Wordpress.
  wordpress.functions:
    class: Prokl\TwigExtensionsPackBundle\Twig\Extensions\Wordpress\WordpressExtension
    tags:
      - { name: twig.extension }

  # apply_filter.
  Prokl\TwigExtensionsPackBundle\Twig\Extensions\ApplyFilterExtension:
    tags:
      - { name: twig.extension }

  # render(). Работает только при установленном роутере.
  twig_extension_bundle.render:
    class: Prokl\TwigExtensionsPackBundle\Twig\Extensions\RenderExtension
    arguments:
      - '@dispatcher.controller'
      - '@routing.utils'
    calls:
      - setContainer: ['@service_container']
    tags:
      - { name: twig.extension }